apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: me7wwnstt-go
  janus-idp.io/tekton: me7wwnstt-go
  backstage.io/kubernetes-id: me7wwnstt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: me7wwnstt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
